import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Tab from "@/components/Tab";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("relative h-full font-mono", inter.className)}>
          <main className="relative flex flex-col min-h-screen">
            <div className="flex-grow flex-1">
              <Tab/>
              {children}
            </div>
          </main>
          
      </body>
    </html>
  );
}
