import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Tab from "@/components/Tab";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add the Geist Mono font */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist+Mono:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={cn("relative h-full font-sans antiliased")}
        style={{ fontFamily: '"Geist Mono", monospace' }} // Set the Geist Mono font
      >
        <main className="relative flex flex-col min-h-screen">
          <div className="flex-grow flex-1">
            <Tab />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
